name: 'wakatime-sync'
description: 'Back up your wakatime sync to your gist'
branding:
  icon: 'clipboard'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
- name: wakatime-sync
  uses: superman66/wakatime-sync@v1.0.0

